# Generated by Django 4.0.2 on 2022-02-21 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='suit'),
        ),
    ]
