# Generated by Django 4.0.2 on 2022-02-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0007_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='rated',
            field=models.BooleanField(default=False),
        ),
    ]
